site_name: "Deranged Senators Documentation"

nav:
    - Home: index.md
    - Overview:
      - Collaborating:
        - collaboration/Get Started.md
        - collaboration/Effective Commits and Code Reviews.md
        - collaboration/Reusable Components.md
        - collaboration/Project Design.md
        - Source Code Design:
            - collaboration/Source Design Document C#.md
    - Cops And Robbers:
        - copsandrobbers/Namespaces/namespaceMe_1_1DerangedSenators_1_1CopsAndRobbers.md
    - PlayerLink:
        - playerlink/Classes/index.md # Temporary... Will be used until a namespace is added to PlayerLink.
theme:
    name: material
    favicon: images/favicon.ico
    features:
        - navigation.tabs
        - toc.integrate
        - navigation.instant
    
    palette:
        - scheme: default
          primary: blue
          accent: light blue
extra:
    social: # Footer SM Links
        - icon: fontawesome/brands/github
          link: https://github.com/DerangedSenators
          name: DerangedSenators on Github
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
copyright: Copyright &copy; 2020 Deranged Senators
