site_name: "Deranged Senators Documentation"

theme:
    name: material
    favicon: images/favicon.ico
    features:
        - navigation.tabs
        - toc.integrate
        - navigation.instant
    
    palette:
        - scheme: default
          primary: blue
          accent: light blue
extra:
    social: # Footer SM Links
        - icon: fontawesome/brands/github
          link: https://github.com/DerangedSenators
          name: DerangedSenators on Github
markdown_extensions:
  - pymdownx.tabbed
  - pymdownx.superfences
copyright: Copyright &copy; 2020 Deranged Senators
