name: Publish Documentation
on:
  push:
  pull_request:
  schedule:
    - cron: '*/240 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Website
        uses: actions/checkout@v2
      - name: Checkout CopsAndRobbers
        uses: actions/checkout@v2
        with:
          repository: derangedsenators/copsandrobbers
          token: ${{ secrets.BUILD_BOT_KEY }}
          path: codedoc/
      - name: Checkout PlayerLink
        uses: actions/checkout@v2
        with:
          repository: derangedsenators/playerlink
          path: codedoc/
      - name: Build Documentation
        shell: bash
        env:
          BUILD_BOT_SECRET: ${{ secrets.BUILD_BOT_KEY }}
        run: |
          ls
          sudo chmod +x getdocs.sh 
          sudo chmod +x doxygen/doxybook2
          echo ${{ secrets.USERNAME }}
          sudo ./getdocs.sh "$BUILD_BOT_SECRET"
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.BUILD_BOT_KEY }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: public # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
