name: Publish Documentation
on:
  push:
  pull_request:
  schedule:
    - cron: '*/240 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Documentation
        shell: bash
        env:
          BUILD_BOT_SECRET: ${{ secrets.BUILD_BOT_KEY }}
        run: |
          ls
          sudo chmod +x getdocs.sh 
          sudo chmod +x doxygen/doxybook2
          echo ${{ secrets.USERNAME }}
          sudo ./getdocs.sh "$BUILD_BOT_SECRET"
      - name: deploy docs
        uses: ./
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.BUILD_BOT_KEY }}
          remote_url: https://github.com/derangedsenators/website.git
